CFLAGS = -g -Wall -Wextra -std=gnu11
BIN = apple

all: $(BIN)

the_apple: the_apple.c 
	gcc $(CFLAGS) the_apple.c -o the_apple

apple: apple.c 
	gcc $(CFLAGS) apple.c -o apple


clear: 
	rm -f apple